### ISSUE TITLE
[US 5] : En tant qu'utilisateur connecté, je souhaite disposer d'une section "playlist" afin de pouvoir trier mes musiques

### ISSUE THREAD

**Issue by YiddishGun11** [YiddishGun11/ShuffleTunes#11]
### Quel est la valeur de la US pour le client

Important

### Description et objectif

l'utilisateur aura la possibilité de consulter la liste de ses playlists ou il aura la possibilité d'y rajouter des sons afin de trier ses musiques 

### Maquettes

1.1 Liste des Playlists

Lorsque l'utilisateur se rend dans l'onglet "playlists" de l'application, celui-ci peux consulter la liste de ses playlists précédemment triées ou sinon se retrouve face à un message lui permettant de savoir qu'il n'a pas encore de playlists

1.2 Listes des playlists + musiques 

Lorsque l'utilisateurs clique sur une playlist, celle-ci s'ouvre de facon "dropdown" et la liste des musique associée à la playlist en question s'affiche

1.3 Créer une playlist

L'utilsateur peux, s'il le veut créer une nouvelle playlist et la rajouter à la liste de ses playlists

### Critères d'acceptation spécifiques à la US

- [x] L'utilisateur à accès à la section "playlist" disponible dans la barre de navigation de l'application
- [x] L'utilisateur à accès à la liste de ses playlists
- [x] L'utilisateur dispose d'un bouton lui permettant de créer une nouvelle playlist
- [x] Lorsque l'utilisateur créer une playlist, celle-ci s'affiche bien dans la liste des playlists lors d'un refresh de la page
- [x] Lorsque l'utilisateur click sur une playlist, il a accès à la liste des musiques de cette playlist
- [x] On ne peut créer qu'une playlist à la fois

- [x] La US respecte le design et la colorimétrie du projet
- [ ] La US passe les testes de vérifications généraux 
- [ ] La US passe ses testes de vérifications spécifiques 

### Tâches techniques qui composent la US

- [x] Création de la page web
- [x] Endpoints API 
- [x] Base de données opérationnelle pour stocker les titres des musiques favorites et ainsi conservé leur état 
- [ ]  Utilisation de procédures

### Estimation du temps de réalisation de la US

Sur une échelle de 1 à 10 et comparé aux autres US, nous plaçons celle ci sur un niveau de difficulté de 8 pour le nombre de critères associés à celle-ci

**Comment by YiddishGun11** [comment]
new issue for US-5 🎉

**Comment by ChaosArnhug** [comment]
C'était ce que tu avais écrit dans le backlog du wiki, comme je l'ai del, je remet la copie ici 

### Musiques favorites
en tant qu'utilisateur connecté, je souhaite disposer d'une section "favoris" afin d'y stocker mes musiques favorites

Responsable : Maisin Edouard

Temps estimé : 8h

Description : l'utilisateur aura la possibilité de consulter une rubrique "favori" reprenant l'ensemble des titres de musique que l'utilisateur auait liké par le passé. Celle-ci permettra d'éviter les recherches récurrentes et d'optimiser l'expérience utilisateur

**Comment by ChaosArnhug** [comment]
Review US v1

`l'utilisateur aura la possibilité de consulter la liste de ses musiques favorites qu'il aura au préalable liké dans le liste de ses musiques afin d'optimiser son expérience utilisateur`

=> au préalable liké OK mais comment marche cette fonctionnalité. Avoir une liste des musiques liké, c'est pas la même chose que de liké une musique. Faut pt faire une US pour expliquer. 

=> J'ai vu ce qu'il se passait si tu dislike dans les critères d'acceptations mais je pense que tu peux l'aborder dans la description aussi. 

=> Peut-on dislike dans la section favoris ou doit-on revenir dans la liste des musiques pour le faire. + Est-ce qu'on pourra like ou dislike dans les playlists ? Et au final, la section favoris, n'est-ce-pas qu'une playlist ? 
Maquette 

J'ai plus l'impression que tu nous montre comment on like plutôt que la section favoris (2 maquettes pour like, 1 de la section)

===> Je pense qu'il faut une US pour la fonctionnalité like/dislike et un peu plus ce concentrer sur cette fameuse section favoris et ce qu'on peut y faire.

**Comment by YiddishGun11** [comment]
End US-5 🎉
