### ISSUE TITLE
[US 7] : En tant qu'utilisateur connecté je souhaite pouvoir avoir accès à mon profil afin d'y consulter mes informations

### ISSUE THREAD

**Issue by Hellisse** [YiddishGun11/ShuffleTunes#14]
### Quel est la valeur de la US pour le client

Important

### Description et objectif

L'utilisateur aura la possibilité de cliquer sur un bouton situé en haut à droite de la fenêtre d'affichage de son profil afin de pouvoir modifier les informations s'y trouvant.

### Maquette
Page de Profil : 

![Page de profil](https://user-images.githubusercontent.com/92713802/195112101-09238b6f-c253-4861-8835-3f6430df3838.jpg)

### Critères d'acceptation spécifiques à la US
- [x] Un bouton d'affichage de profil sera en haut à droite de l'onglet d'accueil.
- [x] Une fois cliqué, une nouvelle page affichant les informations sur l'utilisateur apparaitra.
- [x] Les informations affichées sont correctes et correspondent bien à l'utilisateur.

### Tâches techniques qui composent la US

- [ ] Mise en place d'une BDD
- [ ] Mise en place d'un serveur
- [ ] Traitement de requêtes GET et POST

### Quel est la complexité de la US

4

### Estimation du temps necessaire pour faire la US

3h

**Comment by ChaosArnhug** [comment]
Review écriture US v1

1. Description et objectif  

`"L'utilisateur aura la possibilité de consulter à tout moment son profil via un bouton et d'y modifier, si besoin, les informations s'y trouvant." `
=> Quels est ce bouton ? Ou est il ?
=> Quels sont ces informations ? Nécessitent-elles un traitement particulier ? Par exemple, éditer un mot de passe est plus complexe que de changer une simple description -> mdp conforme ? mdp sécuriser ? Dans ce cas, ne faudrait-t-il pas  faire une US séparer juste pour la modifictaion de ce champs en particulier ?  

`"En cliquant sur le bouton, l'utilisateur vera un onglet déroulant en haut à droite de l'écran lui affichant son pseudo, mot de passe et un avatar personnalisé"` 
=> OK pour affichage pseudo + avatar mais pourquoi mdp ? c'est pas sécurisé
=> Tu reparles d'un bouton, mais est-ce le même que celui qui permet de modifier les informations utilisateur ? Si pas, ou est le bouton pour modif ?

===> T'a description est encore trop floue et tu as 2 objectifs : modif les informations et afficher ces informations avec une sorte de pop-up. Je pense qu'il faut les séparer en 2 US. Concentre toi uniquement sur le component charger de modifier les informations.

2. Maquette 

Oublie pas de la faire, ça te permettra de visualiser le résultat que tu imagines et t'aideras pour rédiger ta US 

3.  Critères d'acceptation spécifiques à la US

C'est un méli-mélo de 2 objectifs différents (cf. mon commentaire plus haut). 
Tu gagnerais à revoir les critères en te concentrant uniquement sur la modif des informations 

4. Tâches techniques qui composent la US

Pas super d'accord avec la notion de rôle. L'utilisateur A ne peut chipoter qu'aux trucs de A. A voir avec le groupe mais je pense pas qu'on prévois un super utilisateur. 

5. Conclusion 

La US est trop vague et peu claire pour une autre personne que toi. Même si je sais m'imaginer l'esquisse du résultat final, pas sûre que se soit la même que toi. Le faite que tu mélanges 2 objectifs n'aide pas non plus. L'affichage des infos de l'utilisateur c'est une chose et les modifier s'en est une autre. 

Pour terminer, méfie toi de certaines informations à modifier car c'est plus complexes qu'un simple changement de texte. Je pense notamment au mdp et nom d'utilisateur qui ont besoins de traitement de vérification + cryptage pour mdp

**Comment by Hellisse** [comment]
Hey !

J'ai essayé de rendre l'US plus claire et dédiée qu'à une seule tâche.
J'ai pris en compte tes remarques et j'ai donc corrigé les différents paragraphes en fonction.

On a donc une plus grande précision sur les boutons et leur emplacement, un division plus claire sur les limites de cette US (comme je l'ai déjà dit plus haut) et j'ai remove l'aspect de droits.

**Comment by Hellisse** [comment]
> Review écriture US v1
> 
> 1. Description et objectif
> 
> `"L'utilisateur aura la possibilité de consulter à tout moment son profil via un bouton et d'y modifier, si besoin, les informations s'y trouvant." ` => Quels est ce bouton ? Ou est il ? => Quels sont ces informations ? Nécessitent-elles un traitement particulier ? Par exemple, éditer un mot de passe est plus complexe que de changer une simple description -> mdp conforme ? mdp sécuriser ? Dans ce cas, ne faudrait-t-il pas faire une US séparer juste pour la modifictaion de ce champs en particulier ?
> 
> `"En cliquant sur le bouton, l'utilisateur vera un onglet déroulant en haut à droite de l'écran lui affichant son pseudo, mot de passe et un avatar personnalisé"` => OK pour affichage pseudo + avatar mais pourquoi mdp ? c'est pas sécurisé => Tu reparles d'un bouton, mais est-ce le même que celui qui permet de modifier les informations utilisateur ? Si pas, ou est le bouton pour modif ?
> 
> ===> T'a description est encore trop floue et tu as 2 objectifs : modif les informations et afficher ces informations avec une sorte de pop-up. Je pense qu'il faut les séparer en 2 US. Concentre toi uniquement sur le component charger de modifier les informations.
> 
> 2. Maquette
> 
> Oublie pas de la faire, ça te permettra de visualiser le résultat que tu imagines et t'aideras pour rédiger ta US
> 
> 3. Critères d'acceptation spécifiques à la US
> 
> C'est un méli-mélo de 2 objectifs différents (cf. mon commentaire plus haut). Tu gagnerais à revoir les critères en te concentrant uniquement sur la modif des informations
> 
> 4. Tâches techniques qui composent la US
> 
> Pas super d'accord avec la notion de rôle. L'utilisateur A ne peut chipoter qu'aux trucs de A. A voir avec le groupe mais je pense pas qu'on prévois un super utilisateur.
> 
> 5. Conclusion
> 
> La US est trop vague et peu claire pour une autre personne que toi. Même si je sais m'imaginer l'esquisse du résultat final, pas sûre que se soit la même que toi. Le faite que tu mélanges 2 objectifs n'aide pas non plus. L'affichage des infos de l'utilisateur c'est une chose et les modifier s'en est une autre.
> 
> Pour terminer, méfie toi de certaines informations à modifier car c'est plus complexes qu'un simple changement de texte. Je pense notamment au mdp et nom d'utilisateur qui ont besoins de traitement de vérification + cryptage pour mdp

Hey !

J'ai essayé de rendre l'US plus claire et dédiée qu'à une seule tâche.
J'ai pris en compte tes remarques et j'ai donc corrigé les différents paragraphes en fonction.

On a donc une plus grande précision sur les boutons et leur emplacement, un division plus claire sur les limites de cette US (comme je l'ai déjà dit plus haut) et j'ai remove l'aspect de droits.

**Comment by ChaosArnhug** [comment]
J'aime bien l'idée de la pop up qui montre le profil. Par contre pour la modification, je ne l'a ferrais pas de la pop up. Je pense que ça sera plus agréable pour l'utilisateur d'avoir une deuxième component qui s'ouvre s'il souhaite modifier son profil. 
De facto, la pop up serrait une US et le component de modif une autre. 
Si tu veux, on peut en parler demain pendant le cours. 

Pour imager les 2 components : 

La pop up pour voir son profil 
![image](https://user-images.githubusercontent.com/71312671/195340553-663535d0-4d56-4b42-89e4-e476046aa952.png)

Le component de modif de profil 
![image](https://user-images.githubusercontent.com/71312671/195340657-0e07d586-15f4-46cc-acd7-7c3d98ea93af.png)

**Comment by ChaosArnhug** [comment]
Supprimer du groupe
