### ISSUE TITLE
[US 6] :  En tant qu'utilisateur connecté, je souhaite disposer d'une section "favoris" afin d'y stocker mes musiques favorites

### ISSUE THREAD

**Issue by arsium** [YiddishGun11/ShuffleTunes#16]
### Quel est la valeur de la US pour le client

Prioritaire

### Description et objectif

L'utilisateur doit pouvoir liker des chansons depuis ses playlists afin qu'elles puissent aller dans une section nommée 'favorits'

### Maquette

![Avant Suppression](https://github.com/YiddishGun11/ShuffleTunes/blob/main/RessourcesWiki/US6-1.png?raw=true)

![Après suppression](https://github.com/YiddishGun11/ShuffleTunes/blob/main/RessourcesWiki/US6-2.png?raw=true)

### Critères d'acceptation spécifiques à la US

- [x] L'utilisateur à accès à la section "favoris" disponible dans la barre de navigation de l'application
- [x] L'utilisateur à accès à la liste de ses musiques 
- [x] L'utilisateur dispose d'un bouton de forme de coeur lui permettant de liker / disliker la musique de son choix
- [x] Lorsque l'utilisateur like une chanson celle-ci se retrouve dans la liste des 'favoris' et le coeur de like est rempli pour signaler que la chanson à belle et bien été likée
- [x] Lorsque l'utilisateur dislike une chanson celle-ci ne se trouve plus dans la liste des "favoris" et le coeur des like n'est plus rempli
- [x] On ne peut liker qu'une seule chanson à la fois

- [x] La US respecte le design et la colorimétrie du projet
- [ ] La US passe les testes de vérifications généraux 
- [ ] La US passe ses testes de vérifications spécifiques 

### Tâches techniques qui composent la US

- [x] Création de la page web
- [x] endpoints API 
- [x] base de données opérationnelle pour stocker les titres des musiques favorites et ainsi conservé leur état 

### Quel est la complexité de la US

Sur une échelle de  1 à 10, nous avons décidé que cette US représenterait une difficulté de 6.

### Estimation du temps necessaire pour faire la US

6h

**Comment by arsium** [comment]
US Perso

**Comment by YiddishGun11** [comment]
review US-6
