### ISSUE TITLE
[US 7] : En tant que qu'utilisateur connecté, je souhaite pouvoir accéder à mon profil afin de pouvoir voir mes informations personnelles

### ISSUE THREAD

**Issue by M-Momin** [YiddishGun11/ShuffleTunes#27]
### Quel est la valeur de la US pour le client

Important

### Description et objectif

L'utilisateur connecté pourra accéder à ces quelques informations personnelles à l'aide de cette fonctionnalité. Celle-ci permettra d'afficher un petit composant en haut à droite de l'écran de l'utilisateur et reprendra l'image et le pseudo de l'utilisateur actuellement connecté. Un bouton sera également présent en haut à droite du composant afin d'accéder à une page reprenant plus de détails du compte et également une option de modification de ces informations.

Ce composant apparaitra en cliquant sur l’icône "personnage" se trouvant en haut à droite de l'écran. Pour refermé le composant, il faudra recliquer sur l'icône cliqué précédemment pour ouvrir le composant.

### Maquette

Dashboard général :   
![général](https://user-images.githubusercontent.com/94617640/200122152-31f26952-b6a4-4569-84cc-911f447cd2ad.png)
<br>
Cliqué sur l'icône mise en évidence pour faire apparaitre le composant :    
![général-Pointé](https://user-images.githubusercontent.com/94617640/200122158-c328e309-ddab-4f9b-927a-8487edda4071.png)
<br>
Apparition du composant :    
![général-profil](https://user-images.githubusercontent.com/94617640/200122159-f05e7f31-b89e-421a-a765-f6011e110515.png)

### Critères d'acceptation spécifiques à la US

- [x] Respect des colorimétries du site.
- [x] Respect de la police du site. (Poppins)
- [x] Un composant apparait lorsque l'utilisateur connecté clique sur l'icone de type profil placé en haut à droite de composant principal.
- [x] Le composant affiche une image.
- [x] Le composant affiche le pseudo de l'utilisateur connecté.
- [x] Le composant admet un bouton en haut à droite de celui-ci.

### Tâches techniques qui composent la US

- [x] Récupération des informations personnelles nécessaire de l'utilisateur connecté auprès de la base de données.

### Quel est la complexité de la US

5

### Estimation du temps necessaire pour faire la US

5h00

**Comment by YiddishGun11** [comment]
Succesfully merged on 19/12/22
